ランニングアプリの全体的なUIを作成
lion-king-IT/RunnersHigh2 pull request #1
Opened 2021-06-07 13:07 UTC by lion-king-IT

前回と同様にBottomNavigationを用いて、Fragmentの切り替えを行っていく。 
https://github.com/lion-king-IT/RunnersHigh#runnershigh

![image](https://user-images.githubusercontent.com/65647834/121021656-91eea200-c7dc-11eb-96f7-78ca1d2c709f.png)

2021-06-07 13:50 UTC, Naoki-Hidaka commented on app/src/main/java/com/reo/running/runnershigh2/MainActivity.kt
> +    lateinit var binding: ActivityMainBinding
onCreate内でしか使わないのであれば、クラスプロパティじゃなくてメソッドプロパティでいい気がしますね

2021-06-07 13:53 UTC, Naoki-Hidaka requested changes

2021-06-07 13:53 UTC, Naoki-Hidaka commented on app/src/main/res/values/color.xml
> +    <color name="theme_color">#84ffff</color>
多分viewモジュールにcolor resourceがあれば参照できるのでなるべくそっちに移しましょう

2021-06-07 13:53 UTC, Naoki-Hidaka commented on ui/view/src/main/java/com/reo/running/ui/view/screen/GraphFragment.kt
> +    private lateinit var binding: FragmentGraphBinding
メソッドプロパティでいい気がします

2021-06-07 13:53 UTC, Naoki-Hidaka commented on ui/view/src/main/java/com/reo/running/ui/view/screen/GraphFragment.kt
> +        super.onCreateView(inflater, container, savedInstanceState)
これがなきゃ動きませんでした？

2021-06-07 13:53 UTC, Naoki-Hidaka commented on ui/view/src/main/java/com/reo/running/ui/view/screen/GraphFragment.kt
> +        binding = FragmentGraphBinding.inflate(layoutInflater, container, false)
onCreateViewの引数のinflater使った方がいいかもですね

2021-06-07 13:53 UTC, Naoki-Hidaka commented on ui/view/src/main/java/com/reo/running/ui/view/screen/ProfileFragment.kt
> +    private lateinit var binding: FragmentProfileBinding
ditto

2021-06-07 13:53 UTC, Naoki-Hidaka commented on ui/view/src/main/java/com/reo/running/ui/view/screen/ProfileSettingFragment.kt
> +    private lateinit var binding: FragmentProfileSettingBinding
ditto

2021-06-07 13:53 UTC, Naoki-Hidaka commented on ui/view/src/main/java/com/reo/running/ui/view/screen/ResultFragment.kt
> +    lateinit var binding: FragmentResultBinding
ditto

2021-06-07 13:53 UTC, Naoki-Hidaka commented on ui/view/src/main/java/com/reo/running/ui/view/screen/RunFragment.kt
> +    private lateinit var binding: FragmentRunBinding
ditto

2021-06-08 09:49 UTC, lion-king-IT commented on ui/view/src/main/java/com/reo/running/ui/view/screen/GraphFragment.kt
> +        super.onCreateView(inflater, container, savedInstanceState)
消し忘れましたー！

2021-06-08 10:40 UTC, Naoki-Hidaka approved these changes
LGTM!

2021-06-08 10:42 UTC, merged